#!/bin/bash

if [ "$#" -eq "0" ]; then
	echo -e "Please specify at least one file to upload"
	exit 1
fi

LISTMODE="SINGLES"
if [ "$1" == "-l" ]; then
	if [ "$#" -gt "2" ]; then
		LISTMODE="LIST"
	else
		echo -e "Please specify at least one file to upload"
		exit
	fi
fi

filelist="$@"
if [ "$LISTMODE" == "LIST" ]; then
	filelist="${@:2}"
fi

declare -a files
for file in $filelist; do
	filename="${file##*/}"
	echo -e "Uploading $filename..."
	response=$(curl -T $file https://pixeldrain.com/api/file/$filename?anonymous=true --progress-bar | jq -r .id)
	echo -e "File accessible at: https://pixeldrain.com/u/$response"
	echo
	files+=($response)
done

if [ "$LISTMODE" == "LIST" ]; then
	outform='{
"title":"","anonymous":true,"files":[ '
	c="0"
	separator=','
	for id in "${files[@]}"; do
		if [[ "$c" -eq $(($# - 2)) ]]; then
			separator=""
		fi
		outform="$outform{\"id\":\"$id\", \"description\":\"\"}$separator"
		c=$(($c + 1))
	done
	outform="$outform ] }"
	outform=$(echo $outform | jq -r tostring)
	response=$(curl -g -H "Content-Type:application/json" -X POST -d "$outform" https://pixeldrain.com/api/list/ -#L)
	echo -e "File(s) accessible at: https://pixeldrain.com/l/$(echo $response | jq -r .id)"
fi
