#!/bin/bash

if [ "$#" -eq "0" ]; then
	echo -e "Please specify at least one file to upload"
	exit 1
fi

LISTMODE="SINGLES"
if [ "$1" == "-l" ]; then
	if [ "$#" -ge "2" ]; then
		LISTMODE="LIST"
	else
		echo -e "Please specify at least one file to upload"
		exit
	fi
fi

ue() {
	local in=$1
	if [ -z "$in" ]; then read in; fi
	echo $in | jq -sRr '@uri'
}

declare -a files
if [ "$LISTMODE" == "LIST" ]; then
	for file in "${@:2}"; do
		filename="${file##*/}"
		echo -e "Uploading $filename..."
		encoded=$(ue "$filename")
		response=$(curl -T "$file" https://pixeldrain.com/api/file/$encoded?anonymous=true --progress-bar | jq -r .id)
		echo -e "File accessible at: https://pixeldrain.com/u/$response"
		echo
		files+=($response)
	done
else
	for file in "$@"; do
		filename="${file##*/}"
		echo -e "Uploading $filename..."
		encoded=$(ue "$filename")
		response=$(curl -T "$file" https://pixeldrain.com/api/file/$encoded?anonymous=true --progress-bar | jq -r .id)
		echo -e "File accessible at: https://pixeldrain.com/u/$response"
		echo
	done
fi

if [ "$LISTMODE" == "LIST" ]; then
	outform='{
"title":"","anonymous":true,"files":[ '
	c="0"
	separator=','
	for id in "${files[@]}"; do
		if [[ "$c" -eq $(($# - 2)) ]]; then
			separator=""
		fi
		outform="$outform{\"id\":\"$id\", \"description\":\"\"}$separator"
		c=$(($c + 1))
	done
	outform="$outform ] }"
	outform=$(echo $outform | jq -r tostring)
	response=$(curl -g -H "Content-Type:application/json" -X POST -d "$outform" https://pixeldrain.com/api/list/ -#L)
	echo -e "File(s) accessible at: https://pixeldrain.com/l/$(echo $response | jq -r .id)"
fi
